### ISSUE TITLE
[BUG] no name when use CustomModelData

### ISSUE THREAD

**Issue by lostINParadies** [BetterGUI-MC/Issue-Tracker#4]
### Type

Plugin

### Specific

NBT, Item, Menu

### Server Software

Paper 1.19.3

### Plugin Version

latest 

### Content

The Name didn't change when using custom NBT Tag

### Steps to reproduce

```bash
name: '&eNächste Seite'
  id: paper
  nbt:
    CustomModelData: 10104
```

### Expected Behaviour

name change

### Actual Behaviour

name don't change

### Screenshots & Links

![Screenshot_5](https://user-images.githubusercontent.com/19432313/215611828-7ece1e9c-6950-44d7-8700-e3f605009b99.png)

**Comment by HSGamer** [comment]
https://bettergui-mc.github.io/Wiki/item-modifier/nbt-modifier.html#note

You should reorder the settings to be `id`, `nbt` and then `name`.
