### ISSUE TITLE
[BUG] Conflict between 2 addons: ItemGotcha & EvalExtra

### ISSUE THREAD

**Issue by dakto101** [BetterGUI-MC/Issue-Tracker#5]
### Type

Addon

### Specific

Menu (give item)

### Server Software

Paper 1.18.2

### Server Information

Plugins:
![image](https://user-images.githubusercontent.com/36808098/217843361-5886f5b7-342b-4acf-a788-565b971f076e.png)

### Plugin Version

8.0

### Content

If you install both ItemGotcha & EvalExtra, ItemGotcha always give you 1 stone block.

### Steps to reproduce

```bash
1. Run 1.18.2 server.
2. Install ItemGotcha, EvalExtra, VaultBridge addons.
3. Config menu like this:


menu-settings:
  name: '&1&ltest'
  rows: 6
  open-action: 'sound: UI_BUTTON_CLICK'
withdraw1:
  COMMAND:
    - 'sound: ENTITY_BAT_TAKEOFF'
    - 'give: EMERALD, 1'    
  LORE:
    - '&a-------------------'
    - '&aWithdraw &a1 Emerald.'
    - '&a-------------------'
  ID: 'EMERALD'
  CLICK-REQUIREMENT:
    DEFAULT:
        withdraw:
            money:
                value: 1
                take: true
            fail-action: 'tell: &cInsufficient balance.'
  KEEP-OPEN: true
  POSITION-X: 2
  POSITION-Y: 2
```

### Expected Behaviour

After removing EvalExtra, it works normally.

### Actual Behaviour

...

**Comment by HSGamer** [comment]
Update EvalExtra to 2.1

And you can always have EvalExtra skip your string by adding `[skip-eval]`
https://bettergui-mc.github.io/Docs/addon/eval-extra/index.html#skip-the-evaluation
